import Header from '@/components/XHeader';

export const metadata = {
	title: 'Catálogo',
	description: 'Generated by create next app',
};

export default function CatalogoLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div>
			<Header />
			<div className='flex h-full'>
				{children}
			</div>
		</div>
	);
}
