import Header from '@/components/XHeader';
import XSidebar from '@/components/XSidebar';

export const metadata = {
	title: 'Catálogo',
	description: 'Generated by create next app',
};

export default function CatalogoLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const items = [
		{name:'Tudo', href: '#'},
		{name:'Rosas do deserto', href: '#'},
		{name:'Vasos plásticos', href: '#'},
		{name:'Vasos de cimento', href: '#'},
		{name:'Fertilizantes', href: '#'},
	]
	return (
		<div>
			<Header />
			<div className='flex h-full'>
				<XSidebar title='Categorias' items={items}/>
				{children}
			</div>
		</div>
	);
}
